# Generated by Django 3.2.7 on 2021-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(max_length=255)),
                ('course_duration', models.IntegerField()),
                ('course_details', models.TextField(max_length=255, null=True)),
                ('coure_cost', models.IntegerField()),
            ],
        ),
    ]
