# Generated by Django 3.2.7 on 2021-09-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='coure_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_name',
            new_name='name',
        ),
    ]
