# Generated by Django 3.2.7 on 2021-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_courses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
