# Generated by Django 3.2.7 on 2021-09-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('detail', models.TextField(null=True)),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
